//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DugoutDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class League
    {
        public League()
        {
            this.Teams = new HashSet<Team>();
        }
    
        public int Id { get; set; }
        public int SportId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Team> Teams { get; set; }
        public virtual Sport Sport { get; set; }
    }
}
